#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include "pgm.h"
#include "bool.h"
#include "threshold.h"
#include "morphology.h"
#include "image_processing.h"
#include "counter.h"
#include "label.h"
